In [14]:
import numpy as np

In [15]:
grid=[[5,3,0,0,7,0,0,0,0],
     [6,0,0,1,9,5,0,0,0],
      [0,9,8,0,0,0,0,6,0],
      [8,0,0,0,6,0,0,0,3],
      [4,0,0,8,0,3,0,0,1],
      [7,0,0,0,2,0,0,0,6],
      [0,6,0,0,0,0,2,8,0],
      [0,0,0,4,1,9,0,0,5],
      [0,0,0,0,8,0,0,7,9]
     
     ]

In [16]:
print(grid)

[[5, 3, 0, 0, 7, 0, 0, 0, 0], [6, 0, 0, 1, 9, 5, 0, 0, 0], [0, 9, 8, 0, 0, 0, 0, 6, 0], [8, 0, 0, 0, 6, 0, 0, 0, 3], [4, 0, 0, 8, 0, 3, 0, 0, 1], [7, 0, 0, 0, 2, 0, 0, 0, 6], [0, 6, 0, 0, 0, 0, 2, 8, 0], [0, 0, 0, 4, 1, 9, 0, 0, 5], [0, 0, 0, 0, 8, 0, 0, 7, 9]]


In [17]:
print(np.matrix(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [18]:
grid[0][0]

5

In [19]:
def possible(y,x,n):
    global grid
    for i in range(0,9):
        if grid[y][i]==n:
            return False
    for i in range(0,9):
        if grid[y][i]==n:
            return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j]==n:
                return False
    return True

In [22]:
possible(1,4,3)

True

In [21]:
possible(3,1,3)

False

In [23]:
def solve():
    global grid
    for y in range(9):
        for x in range(9):
            if grid[y][x]==0:
                for n in range(1,10):
                    if possible(y,x,n):
                        grid[y][x]=n
                        solve()
                        grid[y][x]=0
                return
    print(np.matrix(grid))
    input("More?")
    

In [ ]:
solve()

[[5 3 1 6 7 8 2 4 9]
 [6 2 4 1 9 5 3 7 8]
 [7 9 8 2 3 4 1 6 5]
 [8 1 2 4 6 5 7 9 3]
 [4 6 9 8 7 3 2 5 1]
 [7 3 5 1 2 9 4 8 6]
 [1 6 9 3 5 7 2 8 4]
 [2 7 8 4 1 9 3 6 5]
 [3 4 5 2 8 6 1 7 9]]
More?
[[5 3 1 6 7 8 2 4 9]
 [6 2 4 1 9 5 3 7 8]
 [7 9 8 2 3 4 1 6 5]
 [8 1 2 4 6 5 7 9 3]
 [4 6 9 8 7 3 2 5 1]
 [7 3 5 1 2 9 4 8 6]
 [1 6 9 3 5 7 2 8 4]
 [2 7 8 4 1 9 3 6 5]
 [3 4 5 6 8 2 1 7 9]]
More?
[[5 3 1 6 7 8 2 4 9]
 [6 2 4 1 9 5 3 7 8]
 [7 9 8 2 3 4 1 6 5]
 [8 1 2 4 6 5 7 9 3]
 [4 6 9 8 7 3 2 5 1]
 [7 3 5 1 2 9 4 8 6]
 [1 6 9 3 5 7 2 8 4]
 [2 7 8 4 1 9 3 6 5]
 [3 5 4 2 8 6 1 7 9]]
More?
[[5 3 1 6 7 8 2 4 9]
 [6 2 4 1 9 5 3 7 8]
 [7 9 8 2 3 4 1 6 5]
 [8 1 2 4 6 5 7 9 3]
 [4 6 9 8 7 3 2 5 1]
 [7 3 5 1 2 9 4 8 6]
 [1 6 9 3 5 7 2 8 4]
 [2 7 8 4 1 9 3 6 5]
 [3 5 4 6 8 2 1 7 9]]
More?
[[5 3 1 6 7 8 2 4 9]
 [6 2 4 1 9 5 3 7 8]
 [7 9 8 2 3 4 1 6 5]
 [8 1 2 4 6 5 7 9 3]
 [4 6 9 8 7 3 2 5 1]
 [7 3 5 1 2 9 4 8 6]
 [1 6 9 3 5 7 2 8 4]
 [2 7 8 4 1 9 3 6 5]
 [4 3 5 2 8 6 1 7 9]]
More?
[[5 3 1 6 7 8 2 4 9]

In [1]:
import random
import time
import numpy as np

In [3]:
grid1=[[0,0,0,0,8,0,4,0,7],
     [0,0,8,0,0,4,0,0,0],
     [0,7,0,3,0,6,0,0,0],
     [0,0,0,0,0,0,0,4,2],
     [1,8,0,0,4,0,0,6,5],
     [7,9,0,0,0,0,0,0,0],
     [0,0,0,4,0,7,0,1,0],
     [0,0,0,5,0,0,8,0,0],
     [6,0,3,0,1,0,0,0,0]]
puzzles=[['.','.','.','.',8,'.',4,'.',7],
          ['.','.',8,'.','.',4,'.','.','.'],
          ['.',7,'.',3,'.',6,'.','.','.'],
          ['.','.','.','.','.','.','.',4,2],
          [1,8,'.','.',4,'.','.',6,5],
          [7,9,'.','.','.','.','.','.','.']
          ,['.','.','.',4,'.',7,'.',1,'.'],
          ['.','.','.',5,'.','.',8,'.','.'],
          [6,'.',3,'.',1,'.','.','.','.']]


def display_grid(li):
    count=0
    print("| - - - - - - - - - - - |")
    for i in li:
        for j in i:
            if(count == 0):
                print("|",end=" "),
            print(j, end = " ")
            if(count in [2,5,8]):
                print("|",end=" "),
            count+=1
        print()
        if li.index(i) in [2,5]:
            print("| - - - + - - - + - - - |")
        elif li.index(i) == 8:
            print("| - - - - - - - - - - - |")
        count=0

def has_empty(arr,l):
    for row in range(9):
        for col in range(9):
            if(arr[row][col]=='.'):
                l[0]=row
                l[1]=col
                return True
    return False

def check_horizontal(arr,row,num):
    for i in range(9):
        if(arr[row][i] == num):
            return False
    return True

def check_vertical(arr,col,num):
    for i in range(9):
        if(arr[i][col] == num):
            return False
    return True

def check_group(arr,row,col,num):
    row=row-row%3
    col=col-col%3
    for i in range(3):
        for j in range(3):
            if(arr[i+row][j+col] == num):
                return False
    return True

def check_safe(arr,row,col,num):
    if(check_horizontal(arr,row,num) and check_vertical(arr,col,num) and check_group(arr,row,col,num)):
        return True
    else:
        return False

def solve_puzzle(arr):
    ind=[0,0]
    if(not has_empty(arr,ind)):
        return True
    row=ind[0]
    col=ind[1]
    for num in range(1,10):
        if(check_safe(arr,row,col,num)):
            arr[row][col]=num
            if(solve_puzzle(arr)):
                return True
            arr[row][col] = '.'
    return False

def possible(y,x,n):
    global grid1
    for i in range(0,9):
        if grid1[y][i]==n:
            return False
    for i in range(0,9):
        if grid1[y][i]==n:
            return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if grid1[y0+i][x0+j]==n:
                return False
    return True
if __name__=="__main__":
    grid=puzzles
    print("Puzzle:\n")
    display_grid(grid)
    print("\nSolution :\n")
    start = time.time()
    if(solve_puzzle(grid)):
        display_grid(grid)
        print("\n(Time taken to solve: {} secs)".format(time.time()-start))
    else:
        print ("No solution exists")

Puzzle:

| - - - - - - - - - - - |
| . . . | . 8 . | 4 . 7 | 
| . . 8 | . . 4 | . . . | 
| . 7 . | 3 . 6 | . . . | 
| - - - + - - - + - - - |
| . . . | . . . | . 4 2 | 
| 1 8 . | . 4 . | . 6 5 | 
| 7 9 . | . . . | . . . | 
| - - - + - - - + - - - |
| . . . | 4 . 7 | . 1 . | 
| . . . | 5 . . | 8 . . | 
| 6 . 3 | . 1 . | . . . | 
| - - - - - - - - - - - |

Solution :

| - - - - - - - - - - - |
| 3 6 1 | 9 8 5 | 4 2 7 | 
| 9 2 8 | 1 7 4 | 6 5 3 | 
| 4 7 5 | 3 2 6 | 1 9 8 | 
| - - - + - - - + - - - |
| 5 3 6 | 8 9 1 | 7 4 2 | 
| 1 8 2 | 7 4 3 | 9 6 5 | 
| 7 9 4 | 6 5 2 | 3 8 1 | 
| - - - + - - - + - - - |
| 8 5 9 | 4 3 7 | 2 1 6 | 
| 2 1 7 | 5 6 9 | 8 3 4 | 
| 6 4 3 | 2 1 8 | 5 7 9 | 
| - - - - - - - - - - - |

(Time taken to solve: 1.1003093719482422 secs)


In [6]:
possible(0,1,7)

False

In [7]:
possible(0,0,3)

True

In [8]:
possible(0,1,6)

True

In [10]:
possible(0,1,8)

False

In [8]:
np.matrix(grid)

matrix([[3, 1, 6, 5, 7, 8, 4, 9, 2],
        [5, 2, 9, 1, 3, 4, 7, 6, 8],
        [4, 8, 7, 6, 2, 9, 5, 3, 1],
        [2, 6, 3, 4, 1, 5, 9, 8, 7],
        [9, 7, 4, 8, 6, 3, 1, 2, 5],
        [8, 5, 1, 7, 9, 2, 6, 4, 3],
        [1, 3, 8, 9, 4, 7, 2, 5, 6],
        [6, 9, 2, 3, 5, 1, 8, 7, 4],
        [7, 4, 5, 2, 8, 6, 3, 1, 9]])

In [4]:
possible(0,1,1)

False

In [3]:
grid=[[0,0,0,0,8,0,4,0,7],
     [0,0,8,0,0,4,0,0,0],
     [0,7,0,3,0,6,0,0,0],
     [0,0,0,0,0,0,0,4,2],
     [1,8,0,0,4,0,0,6,5],
     [7,9,0,0,0,0,0,0,0],
     [0,0,0,4,0,7,0,1,0],
     [0,0,0,5,0,0,8,0,0],
     [6,0,3,0,1,0,0,0,0]]
np.matrix(grid)

matrix([[0, 0, 0, 0, 8, 0, 4, 0, 7],
        [0, 0, 8, 0, 0, 4, 0, 0, 0],
        [0, 7, 0, 3, 0, 6, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 4, 2],
        [1, 8, 0, 0, 4, 0, 0, 6, 5],
        [7, 9, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 4, 0, 7, 0, 1, 0],
        [0, 0, 0, 5, 0, 0, 8, 0, 0],
        [6, 0, 3, 0, 1, 0, 0, 0, 0]])